id = "example.arc_arsenal"
name = "Arc Arsenal Example"
version = "0.1.0"
author = "Project RL"
game_version = ">=0.1.0, <0.2.0"

dependencies = [
    "core >=0.1.0, <0.2.0"
]
optional_dependencies = []
incompatible = []
